from __future__ import annotations

import json
import os
import re
import urllib.error
import urllib.request
from decimal import Decimal, InvalidOperation
from typing import Any

from .engine import Claim, EvidenceReport


CITATION_PATTERN = re.compile(r"\[(EV-[A-Z]+-\d{3})\]")

# Appended by the application to every accepted narrative. The model may not
# state, soften or negate decision rights itself.
BOUNDARY_STATEMENT = (
    "This explanation is not authoritative: the deterministic evidence report is, and any "
    "budget action requires a recorded decision by the accountable budget owner."
)

SENTENCE_SPLIT = re.compile(r"(?<=[.!?;])\s+|\n+")
BOUNDARY_LANGUAGE = re.compile(
    r"\b(approv\w*|authori[sz]\w*|execut\w*|sign[- ]?off|permission\w*)\b", re.IGNORECASE
)
# A lexical filter cannot catch every paraphrase. It narrows what can pass; the
# narrative stays optional and non-authoritative because this list is incomplete.
PROHIBITED_LANGUAGE = re.compile(
    r"\b(guarantee\w*|caus\w*|dr[io]v\w*|led to|leads? to|result(?:s|ed)? in|thanks to|"
    r"responsible for|generated by|incremental\w*|prov(?:e|es|ed|en|ing)|roi|"
    r"return on investment|will|forecast\w*|predict\w*|reallocat\w*|automatic\w*|autonom\w*)\b",
    re.IGNORECASE,
)
# Quantities written in words, or relative to another figure, bypass numeric
# matching entirely, so they are refused. "one" is allowed as ordinary English.
QUANTITY_WORDS = re.compile(
    r"\b(zero|nil|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|"
    r"fifteen|sixteen|seventeen|eighteen|nineteen|twenty|thirty|forty|fifty|sixty|seventy|eighty|"
    r"ninety|hundreds?|thousands?|lakhs?|crores?|half|double|twice|triple|treble|quadruple)\b",
    re.IGNORECASE,
)
# Every channel figure is assumption-dependent; ranking or judging channels on it
# is the unreliable optimisation the report explicitly declines to support.
RANKING_LANGUAGE = re.compile(
    r"\b(best|worst|better|worse|outperform\w*|underperform\w*|strongest|weakest|highest|lowest|"
    r"top|bottom|winn\w*|los(?:er|ers|ing)|superior|inferior|clearly|obviously|definitely|certainly)\b",
    re.IGNORECASE,
)
DATE_PATTERN = re.compile(r"\b\d{4}-\d{1,2}-\d{1,2}\b|\b\d{1,2}/\d{1,2}/\d{2,4}\b")
ABBREVIATED_AMOUNT = re.compile(
    r"\d[\d,]*(?:\.\d+)?\s*(?:k|m|mn|bn|b|thousand|million|billion)\b", re.IGNORECASE
)
NUMBER = re.compile(
    r"(?P<currency>\bAED\s*)?(?P<sign>[-−+])?"
    r"(?P<number>\d{1,3}(?:,\d{3})+(?:\.\d+)?|\d+(?:\.\d+)?)"
    r"(?:\s*(?P<unit>%|per\s?cent\b|percent\b|×|x\b|days?\b))?",
    re.IGNORECASE,
)
PLAIN_NUMBER = re.compile(r"\d+(?:\.\d+)?")


def evidence_payload(report: EvidenceReport) -> dict[str, Any]:
    """Computed evidence values only: no source rows and no row references."""
    fields = ("evidence_id", "metric", "value", "unit", "grade", "explanation", "assumptions", "dimensions")
    return {"claims": [{field: getattr(claim, field) for field in fields} for claim in report.claims]}


def finalize_narrative(text: str) -> str:
    return f"{text.strip()}\n\n{BOUNDARY_STATEMENT}"


def _unit(match: re.Match[str]) -> str | None:
    unit = re.sub(r"\s+", "", (match.group("unit") or "").lower())
    if unit in {"%", "percent"}:
        return "percent"
    if unit in {"×", "x"}:
        return "ratio"
    if unit.startswith("day"):
        return "days"
    if match.group("currency"):
        return "AED"
    return None


def _supported(match: re.Match[str], cited: list[Claim]) -> bool:
    """A number is supported only by the value, or a numeric qualifier, of a claim cited beside it."""
    if match.group("sign"):
        return False
    value = Decimal(match.group("number").replace(",", ""))
    unit = _unit(match)
    for claim in cited:
        if unit in (None, "days") and any(
            PLAIN_NUMBER.fullmatch(qualifier) and Decimal(qualifier) == value
            for qualifier in claim.dimensions.values()
        ):
            return True
        if unit == "days" or (unit is not None and unit != claim.unit):
            continue
        try:
            if Decimal(claim.value) == value:
                return True
        except InvalidOperation:
            continue
    return False


def validate_narrative(text: str, report: EvidenceReport) -> tuple[bool, str]:
    if not text or not text.strip():
        return False, "narrative is empty"
    if not CITATION_PATTERN.search(text):
        return False, "narrative contains no evidence citations"
    claims = {claim.evidence_id: claim for claim in report.claims}

    for sentence in (part.strip() for part in SENTENCE_SPLIT.split(text)):
        if not sentence:
            continue
        cited_ids = list(dict.fromkeys(CITATION_PATTERN.findall(sentence)))
        unknown = sorted(set(cited_ids) - set(claims))
        if unknown:
            return False, f"narrative cites unknown evidence IDs: {unknown}"
        cited = [claims[evidence_id] for evidence_id in cited_ids]

        remainder = CITATION_PATTERN.sub(" ", sentence)
        if re.search(r"EV-", remainder, re.IGNORECASE):
            return False, f"malformed evidence citation in: {sentence!r}"
        labels = {
            qualifier
            for claim in cited
            for qualifier in claim.dimensions.values()
            if not PLAIN_NUMBER.fullmatch(qualifier)
        }
        for label in sorted(labels, key=len, reverse=True):
            remainder = re.sub(re.escape(label), " ", remainder, flags=re.IGNORECASE)

        if BOUNDARY_LANGUAGE.search(remainder):
            return False, (
                "narrative must not discuss approval or execution; the application states that boundary"
            )
        prohibited = PROHIBITED_LANGUAGE.search(remainder)
        if prohibited:
            return False, (
                "narrative contains prohibited causal, forecast, guarantee, ROI or autonomy wording: "
                f"{prohibited.group(0)!r}"
            )
        quantity = QUANTITY_WORDS.search(remainder)
        if quantity:
            return False, (
                f"spelled-out or relative quantities cannot be verified: {quantity.group(0)!r}"
            )
        ranking = RANKING_LANGUAGE.search(remainder)
        if ranking:
            return False, (
                "narrative must not rank or judge channels on assumption-dependent evidence: "
                f"{ranking.group(0)!r}"
            )
        if DATE_PATTERN.search(remainder):
            return False, f"narrative must not state dates: {sentence!r}"
        if ABBREVIATED_AMOUNT.search(remainder):
            return False, f"abbreviated amounts cannot be verified: {sentence!r}"

        numbers = list(NUMBER.finditer(remainder))
        if numbers and not cited:
            return False, f"sentence states a number without citing evidence: {sentence!r}"
        for match in numbers:
            if not _supported(match, cited):
                values = ", ".join(f"{claim.evidence_id}={claim.value} {claim.unit}" for claim in cited)
                return False, (
                    f"{match.group(0).strip()!r} does not match any value cited in the same sentence ({values})"
                )
    return True, "validated"


def generate_azure_narrative(report: EvidenceReport) -> dict[str, str]:
    endpoint = os.getenv("AZURE_OPENAI_ENDPOINT", "").rstrip("/")
    deployment = os.getenv("AZURE_OPENAI_DEPLOYMENT", "")
    api_key = os.getenv("AZURE_OPENAI_API_KEY", "")
    api_version = os.getenv("AZURE_OPENAI_API_VERSION", "2024-10-21")
    if not all((endpoint, deployment, api_key)):
        return {
            "status": "disabled",
            "reason": "Azure configuration is incomplete",
            "content": "",
        }
    system = (
        "Explain only the supplied computed evidence records. Every sentence that contains a number "
        "must cite, in square brackets inside that same sentence, the evidence ID whose value it states, "
        "and must copy that value exactly (thousands separators allowed; no rounding, abbreviations, "
        "signs, dates or numbers written in words). Do not rank, compare or judge channels. Do not "
        "describe causation, incrementality, forecasts, guarantees, ROI, budget "
        "changes, approval or execution. Do not repeat the decision-rights statement; the application "
        "adds it."
    )
    body = json.dumps(
        {
            "messages": [
                {"role": "system", "content": system},
                {
                    "role": "user",
                    "content": json.dumps(evidence_payload(report), ensure_ascii=False),
                },
            ],
            "temperature": 0,
            "max_tokens": 650,
        }
    ).encode("utf-8")
    url = f"{endpoint}/openai/deployments/{deployment}/chat/completions?api-version={api_version}"
    request = urllib.request.Request(
        url,
        data=body,
        headers={"Content-Type": "application/json", "api-key": api_key},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            payload = json.loads(response.read().decode("utf-8"))
        text = payload["choices"][0]["message"]["content"]
    except (urllib.error.URLError, KeyError, ValueError, TimeoutError) as exc:
        return {"status": "disabled", "reason": f"Azure request failed: {exc}", "content": ""}
    valid, reason = validate_narrative(text, report)
    return {
        "status": "validated" if valid else "disabled",
        "reason": reason,
        "content": finalize_narrative(text) if valid else "",
    }
